/* SPDX-License-Identifier: (GPL-2.0-only OR BSD-2-Clause) */
/*
 * Copyright 2026 Linaro Ltd.
 *
 * Device Tree binding constants for Exynos850 ACPM clock controller.
 */

#ifndef _DT_BINDINGS_CLOCK_SAMSUNG_EXYNOS850_ACPM_H
#define _DT_BINDINGS_CLOCK_SAMSUNG_EXYNOS850_ACPM_H

#define EXYNOS850_CLK_ACPM_DVFS_MIF			0
#define EXYNOS850_CLK_ACPM_DVFS_INT			1
#define EXYNOS850_CLK_ACPM_DVFS_CPUCL0			2
#define EXYNOS850_CLK_ACPM_DVFS_CPUCL1			3
#define EXYNOS850_CLK_ACPM_DVFS_G3D			4
#define EXYNOS850_CLK_ACPM_DVFS_AUD			5
#define EXYNOS850_CLK_ACPM_DVFS_CAM			6
#define EXYNOS850_CLK_ACPM_DVFS_DISP			7
#define EXYNOS850_CLK_ACPM_DVFS_CP			8

#endif /* _DT_BINDINGS_CLOCK_SAMSUNG_EXYNOS850_ACPM_H */
